### ISSUE TITLE
How to show & hide navbar on scroll

### ISSUE THREAD

**Issue by dejan-77** [locomotivemtl/locomotive-scroll#127]
Hi guys, is it possible to create show & hide navbar (or any div). on scroll down hides and on scroll up navbar shows. Here's a preview of what I want to achieve 
Thanks !!! :)

https://youtu.be/a2Kp4bSDCwI

**Comment by Jerek0** [comment]
That's something you can achieve in multiple ways.
You can use `html[data-direction="down"]` to hide your element via CSS. 
Or you can use the `scroll` event with javascript to build your own logic of showing/hiding your element.

But there is no "prebuilt" option for that in LS, you'll have to get your hands dirty 😉

**Comment by dejan-77** [comment]
Thank you :)
i'm newbie and doing my best to catch up with everything you have said. i'm interested in option one, hiding with CSS and i tried to Google html[data-direction="down"] but nothing came out. can you point me in right direction, please? 
The other method... i'm familiar with triggering with calls, but still trying to figure out how to trigger navbar down immediately after user scrolls up, not after call trigger. Hopefully you can give me more hints :))

**Comment by Jerek0** [comment]
@dejan-77 Assuming `#yournavbar` is outside of the `data-scroll-container`, the CSS I proposed would look like that:

```CSS
#yournavbar {
  position: fixed;
  top: 0; left: 0;
  transform: translate3d(0,0,0);
  transition: transform .5s ease-in-out;
}

html[data-direction="down"] #yournavbar {
  transform: translate3d(0,-100%,0);
}
```

For that to work you also need to specify the `getDirection` option to `true` when instancing LS 😉
