### ISSUE TITLE
Some elements disappear

### ISSUE THREAD

**Issue by esterfrontend** [locomotivemtl/locomotive-scroll#435]
Hello 👋

**Describe the bug**
When scroll down some elements disappear and they suddenly appear when scrolling up.

**Screenshots**
Youtube video to see the trouble on chrome.
https://www.youtube.com/watch?v=Tfuvsa-64f8

**Desktop:**
 - OS:  iOS
 - Browser: chrome, firefox
 - Version 4.1.4

I could fix it on Chrome using:
```
.has-scroll-smooth [data-scroll-container] {
    transform: perspective(1px);
}
```
This fix is not working in firefox.

Thank you 👊

**Comment by naptestdev** [comment]
This trick works well for me

```css
[data-scroll-container] {
  perspective: 999999px !important;
}
```
